version: '3.8'

services:
  api:
    build: .
    container_name: agent_finder_api
    ports:
      - "8004:8004"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - API_V1_PREFIX=${API_V1_PREFIX}
      - PROJECT_NAME=${PROJECT_NAME}
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8004 --reload
    restart: unless-stopped