version: "3.8"

services:
  property-recommendation:
    build: .
    ports:
      - "8011:8011"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "https://34.72.69.249:8011/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
